config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'

  devise_for :users,
					path: '',
					path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
	controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations'}

	resources :users, only: [:show]
	resources :rooms, except: [:edit] do
		member do
			get 'listing'
			get 'pricing'
			get 'summary'
			get 'photo_upload'
			get 'amenities'
			get 'location'
			get 'preload'
			get 'preview'
		end
		resources :photos, only: [:create, :destroy]
		resources :reservations, only: [:create]


	end
  # devise_for :installs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/your_trips' => 'reservations#your_trips'
	get '/your_reservations' => 'reservations#your_reservations'
	get 'search' => 'pages#search'
	# get 'rooms/index' => 'rooms#index'
	# get 'update' => 'rooms#update'


end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
	has_many :photos, dependent: :destroy
	has_many :reservations, dependent: :destroy

	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	validates :home_type, presence: true
	validates :room_type, presence: true
	validates :accommodate, presence: true
	def is_ready?
		!price.blank? && !listing_name.blank? && !photos.blank? && !address.blank? && !summary.blank?
	end
	def cover_photo(size)
		if self.photos.length > 0
			self.photos[0].image.url()
		else
			"blank.jpg"
		end
	end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
	before_action :set_room, except [:index, :new, :create]

	before_action :authenticate_user!, except: [:show]

	def index
		@rooms = current_user.rooms
  end

  def new
		@room = current_user.rooms.build
  end

  def create
		@room = current_user.rooms.build(room_params)
		if @room.save
			redirect_to listing_room_path(@room), notice: "Saved..."
		else
			render :new, notice: "Something went wrong..."
		end
  end

	def show
	end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def update
		if @room = Room.find(room_params)
			flash[:notice] = "Saved"
		else
			redirect_back(fallback_location: request.referer)
		end
  end

	private
		def set_room
			@room = Room.find(params[:id])
		end

		def room_params
			params.require(:room).permit(:home_type, :room_type, :accomodate, :listing_name, :summary, :address, :is_tv, :is_quiet,
       :is_coffee_tea, :is_snacks, :is_wifi, :is_bw_printing, :is_color_printing, :is_bw_copying, :is_color_copying, :is_pet_friendly, :is_fridge, :is_parking, :price, :active)
		end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :set_room, except: [:index, :new, :create]

	before_action :authenticate_user!, except: [:show]
	before_action :is_authorized, only: [:listing, :pricing, :summary, :photo_upload, :amenities, :location, :update]

	def index
		@rooms = current_user.rooms
  end

  def new
		@room = current_user.rooms.build
  end

  def create
		@room = current_user.rooms.build(room_params)
		if @room.save!
			redirect_to listing_room_path(@room), notice: "Saved..."
		else
			flash[:alert] = "Something went wrong..."
			render :new
		end
  end

	def show
		@photos = @room.photos
	end

  def listing
  end

  def pricing
		@price = @room.price
  end

  def summary
  end

  def photo_upload
		@photos = @room.photos
  end

  def amenities

  end

  def location
		# redirect_to location_room_path
  end

  def update
		new_params = room_params
		new_params = room_params.merge(active: true) if is_ready_room

		if @room.update(new_params)
			flash[:notice] = "Saved..."
			if @room.active == true
				redirect_to rooms_path
			else
				redirect_back(fallback_location: request.referer)
			end
			# redirect_to @room
		else
			flash[:alert] = "Something went wrong..."
			redirect_back(fallback_location: request.referer)
		end

  end

	# RESERVATIONS
	def preload
		today = Date.today
		reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

		render json: reservations
	end

	# gets 'preview added to controller'
	def preview
		start_date = Date.parse(params[:start_date])
		end_date = Date.parse(params[:end_date])

		output = {
			conflict: is_conflict(start_date, end_date, @room)
		}

		render json: output
	end
	########
	####NEEDS REDIRECT AFTER COMPLETION
	#######
	private

	#RE DATEPICKER - NEED TIME PICKER
	def is_conflict(start_date, end_date, room)
		check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
		check.size > 0 ? true : false
	end

	def set_room
		@room = Room.find(params[:id])

	end

	def is_authorized
		redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id

	end

	def is_ready_room
		!@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? && !@room.summary.blank?
	end

	def room_params
		params.require(:room).permit(:home_type, :room_type, :accommodate, :listing_name, :summary, :address, :is_tv, :is_quiet,
     :is_coffee_tea, :is_snacks, :is_wifi, :is_bw_printing, :is_color_printing, :is_bw_copying, :is_color_copying, :is_pet_friendly, :is_fridge, :is_parking, :price, :active)
	end
	# def room_2_params
	# 	params.require(:room).permit()
	# end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
		<%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
		<% if !@room.price.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Description", summary_room_path, class: "sidebar-link active" %><% if !@room.listing_name.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %> <% if !@room.photos.blank? %>
		<span id="photo-check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Location", location_room_path, class: "sidebar-link active" %><% if !@room.address.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>
</ul>
<hr/>



<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
	<%= f.hidden_field :active, value: true %>
	<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !@room.is_ready? %>
<% end %>

app/views/rooms/_room_menu.html_BACKUP_3388.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
		<%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
		<span class="text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
		<% if !@room.price.blank? %>
		<span class="text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Description", summary_room_path, class: "sidebar-link active" %><% if !@room.listing_name.blank? %>
		<span class="text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %> <% if !@room.photos.blank? %>
		<span id="photo-check" class="text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
		<span class="text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Location", location_room_path, class: "sidebar-link active" %><% if !@room.address.blank? %>
		<span class="text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>
</ul>
<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
	<%= f.hidden_field :active, value: true %>
	<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !@room.is_ready? %>
<% end %>

app/views/rooms/_room_menu.html_BASE_3388.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
		<%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
		<% if !@room.price.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Description", summary_room_path, class: "sidebar-link active" %><% if !@room.listing_name.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %> <% if !@room.photos.blank? %>
		<span id="photo-check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Location", location_room_path, class: "sidebar-link active" %><% if !@room.address.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>
</ul>
<hr/>



<!-- MAY CONFLICT W PATCH METHOD IN MODELS -->
<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
	<%= f.hidden_field :active, value: true %>
	<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !@room.is_ready? %>
	<!-- CONFLICT CONTINUED - REMOVE @ -->
<% end %>

app/views/rooms/_room_menu.html_REMOTE_3388.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
		<%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
		<% if !@room.price.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Description", summary_room_path, class: "sidebar-link active" %><% if !@room.listing_name.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %> <% if !@room.photos.blank? %>
		<span id="photo-check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Location", location_room_path, class: "sidebar-link active" %><% if !@room.address.blank? %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>
</ul>
<hr/>



<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
	<%= f.hidden_field :active, value: true %>
	<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !@room.is_ready? %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag room.cover_photo(:medium) %>
        </div>
        <div class="panel-body">
          <%= link_to room.listing_name, room %><br/>
          $<%= room.price %> - <%= room.home_type %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Amenities
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @room do |f| %>

					<div class="row form-group">
						<div class="col-md-4">
							<%= f.check_box :is_tv %> TV
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_quiet %> Quiet
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_coffee_tea %> Coffee/Tea
						</div>
					</div>

					<div class="row form-group">
						<div class="col-md-4">
							<%= f.check_box :is_snacks %> Snacks
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_wifi %> Wifi
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_bw_printing %> Black and White Printing
						</div>
					</div>

					<div class="row form-group">
						<div class="col-md-4">
							<%= f.check_box :is_color_printing %> Color Printing
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_bw_copying %> Black and White Printing
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_color_copying %> Color Printing
						</div>
					</div>

					<div class="row form-group">
						<div class="col-md-4">
							<%= f.check_box :is_pet_friendly %> Pets Allowed
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_parking %> Onsite Parking
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_fridge %> Refrigerator
						</div>
					</div>
					<br><br>
					<div class="text-center">
						<%= f.submit "Save", class: "btn btn-form" %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/description.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Description
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @room do |f| %>

					<div class="row">
						<div class="form-group">
							<label for="">Listing Name</label>
							<%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
						</div>
					</div>

					<div class="row">
						<div class="form-group">
							<label for="">Summary</label>
							<%= f.text_area :summary, rows: 5, placeholder: "Describe the workspace", class: "form-control", required: true %>
						</div>
					</div>

					<div class="text-center">
						<%= f.submit "Save", class: "btn btn-form" %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your listings", room_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
			<li class="sidebar-item">
				<%= link_to "Your Office Plans", your_trips_path, class: "sidebar-link" %>
			</li>
		</ul>
	</div>

	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">

				<% @rooms.each do |room| %>
					<div class="row">
						<div class="col-md-2">
					<%= image_tag room.cover_photo(:thumb), :size => "260x180" %>
						</div>
							<!-- listing name -->
						<div class="col-md-7">
							<h4><%= room.listing_name %></h4>
						</div>
						<div class="col-md-3 right">
	             <%= link_to "Update", listing_room_path(room),class: "btn btn-form" %>
	           </div>
					</div>
					<hr/>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Listing
			</div>

			<div class="panel-body">
				<div class="container">
					<% form_for @room do |f| %>

						<div class="row">
							<div class="col-md-4 select">
								<div class="form-group">
									<label for="">Home Type</label>
									<%= f.select :home_type, [["House", "House"], ["Apartment", "Apartment"], ["Other", "Other"]],
									id: "home_type", prompt: "Select...", class: "form-control" %>
								</div>
							</div>

							<div class="col-md-4 select">
								<div class="form-group">
									<label for="">Office Type</label>
									<%= f.select :room_type, [["Living Room", "Living Room"], ["Dining Room", "Dining Room"], ["Private Room", "Private Room"], ["Other", "Other"]],
									id: "room_type", prompt: "Select...", class: "form-control"  %>
								</div>
							</div>

							<div class="col-md-4 select">
								<div class="form-group">
									<label for="">Accommodate</label>
									<%= f.select :home_type, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
									id: "accommodate", prompt: "Select...", class: "form-control"  %>
								</div>
							</div>
							
						</div>
						<div>
						<%= f.submit "Save", class: "btn btn-normal" %></div>
						<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Create Your Shared Office
	</div>
	<div class="panel-body">
		<div class="container">

			<%= form_for @room do |f| %>

				<div class="row">
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Home Type</label>
							<%= f.select :home_type, [["House", "House"], ["Apartment", "Apartment"], ["Other", "Other"]],
							id: "home_type", prompt: "Select...", class: "form-control"  %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Office Type</label>
							<%= f.select :room_type, [["Living Room", "Living Room"], ["Dining Room", "Dining Room"], ["Private Room", "Private Room"], ["Other", "Other"]],
							id: "room_type", prompt: "Select...", class: "form-control"  %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label for="">Accommodate</label>
							<%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
							id: "accommodate", prompt: "Select...", class: "form-control"  %>
						</div>
					</div>
					
				</div>
				<div><%= f.submit "Create My Office", class: "btn btn-normal" %></div>
			<% end %>
		</div>
	</div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Photos
			</div>

			<div class="panel-body">
				<div class="container">
					<div class="row">
						<div class="col-md-offset-3 col-md-6">
							<!-- PHOTO UPLOADS WILL GO HERE -->
							<%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
								<div class="row">
									<div class="form-group">
										<span class="btn btn-default btn-file text-babu">
											<i class="fa fa-cloud-upload", aria-hidden="true"></i>
											Select Photos<%= file_field_tag "images[]", type: :file, multiple: true %>
										</span>

									</div>
								</div>

								<div class="text-center">
									<%= f.submit "Add Photos", class: "btn btn-form" %>
								</div>
							<% end %>
						</div>
					</div>
					<div id="photos"><%= render 'photos/photos_list' %></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>

	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Pricing
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @room do |f| %>
						<div class="row">


							<div class="form-group">
								<label>Price</label>
								<%= f.text_field :price, placeholder: "e.g. $12", class: "form-control", required: true %>
							</div>
						</div>

						<div class="text-center">
							<%= f.submit "Save", class: "btn btn-form" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/summary.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Description
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @room do |f| %>

					<div class="row">
						<div class="form-group">
							<label for="">Listing Name</label>
							<%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
						</div>
					</div>

					<div class="row">
						<div class="form-group">
							<label>Summary</label>
							<%= f.text_area :summary, rows: 5, placeholder: "Describe the workspace", class: "form-control", required: true %>
						</div>
					</div>

					<div class="text-center">
						<%= f.submit "Save", class:"btn btn-form" %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/update.html.erb
<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading">
			Listings
		</div>
		<div class="panel-body">

			<% @rooms.each do |room| %>
				<div class="row">
					<div class="col-md-2">
						<%= image_tag room.cover_photo(:thumb) %>
					</div>
					<div class="col-md-7">
						<h4><%= room.listing_name %></h4>
					</div>
					<div class="colo-md-3 right">
						<%#= link_to "Update", update_rooms_path(room), class: "btn btn-form" %>
					</div>
				</div>
				<hr>
			<% end %>
		</div>
	</div>
</div>